### ISSUE TITLE
INFOGRAFIA_CICLO DE VIDA DEL DESARROLO DE UN SOFTWARE

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/actividad-1-infografia-magaly1311#2]
[INFOGRAFIA CICLO DE VIDA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-magaly1311/files/9446529/INFOGRAFIA.CICLO.DE.VIDA.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
